name: Docker Image CI

on:
  push:
    branches: [ master ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag felixengelmann/lidl-connect-exporter:latest
    - name: Push the tagged Docker image
      run: docker push felixengelmann/lidl-connect-exporter:latest
